### ISSUE TITLE
设置房间页面最后一页提交无响应，无法保存

### ISSUE THREAD

**Issue by KernSSSS** [MemoriesOfTime/CrystalWars#33]
![image](https://user-images.githubusercontent.com/23436744/159906766-1a6fa6f4-3f74-45c6-9a80-043a1c7669e5.png)

**Comment by lt-name** [comment]
请说明说使用的插件版本以及gamecore的版本

**Comment by KernSSSS** [comment]
补充：插件 0.4.2，客户端 1.18.12 ，服务端1.18.10 Nukkit .
新问题：死亡后观察者模式可破坏方块，稍后我会在群里@并给出对应视频

**Comment by lt-name** [comment]
https://ci.lt-name.cn/view/Memories%20Of%20Time/job/CrystalWars/job/master/
从这里下载最新构建试下
0.4.3快照版本 修复了很多bug
