### ISSUE TITLE
退出房间执行命令功能失效

### ISSUE THREAD

**Issue by szzz666** [MemoriesOfTime/CrystalWars#44]
Nukkit PM1E 1.19.80.2964服务端
是在你的构建站下载的
![image](https://github.com/MemoriesOfTime/CrystalWars/assets/60167194/f18d0d49-8b34-4119-af9b-df4cd1e7eeb3)
这个
退出房间执行命令功能失效
没有报错
HotPotato_Nukkit和CrystalWars插件都有这个问题

**Comment by lt-name** [comment]
水晶战争还没有加这个功能，等我有空加上

**Comment by szzz666** [comment]
ok，加上了告诉我

**Comment by lt-name** [comment]
更新到最新快照测试
